FROM ubuntu:22.04 AS builder

LABEL maintainer="Tod Kurt <tod@todbot.com>"
LABEL description="Build stage for blink1-tool"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -y \
        build-essential \
        git \
        pkg-config \
        libudev-dev \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/blink1

# Copy local source code into container
COPY . .

RUN make clean && make blink1-tool && make blink1-tiny-server


# --- Stage 2: Minimal runtime ---
FROM ubuntu

LABEL maintainer="Tod Kurt <tod@todbot.com>"
LABEL description="Minimal runtime image for blink1-tool"

# Copy the compiled binary from builder
COPY --from=builder /opt/blink1/blink1-tool /usr/local/bin/blink1-tool
COPY --from=builder /opt/blink1/blink1-tiny-server /usr/local/bin/blink1-tiny-server

# Install runtime dependencies (libusb)
RUN apt-get update && apt-get install -y libusb-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8934

# Default command
CMD ["blink1-tool"]


